name: 请求适配
title: '[Feature] '
description: 请求增加适配 APP 规则
body:
  - type: markdown
    attributes:
      value: |
        ## ⚠️在提交问题之前，请您务必完成以下操作，否则你的issue可能会根据情况直接被关闭❗❗❗

        1. **提供需要适配界面的快照📸，快照获取方式如下图**
        
        > [!WARNING]
        >   - 不要提供截图，截图对编写规则**没有任何作用❗**
        >   - 不要使用**截屏快照**
        
        2. 请务必阅读 [不予适配情况合集](https://github.com/Lin-arm/GKD_subscription/issues/17)
        3. **如果是需要多次/逐步点击才能关闭或生效的情况**（如分段广告、步骤式弹窗、多步操作功能类规则），请务必提供**每一步点击的快照**
        4. 检查全局规则是否开启
        5. 检查使用的是否是 [最新版订阅](https://github.com/Lin-arm/GKD_subscription/releases/latest) 和 [最新版GKD](https://github.com/gkd-kit/gkd/releases)
        6. 如果你的issue被受理，受理者提出的问题、要求，应在3日内予以回复，否则会被关闭
  - type: textarea
    id: feature-description
    attributes:
      label: |
        📸请提供 需要适配界面 的快照（不要提供截图！！！不要使用截屏快照！！！），也可补充说明
      description: |
        快照是一个 zip 文件，快照链接是类似 "https://i.gkd.li/i/XXXXXXXX" 的文本，按照如下方式可获得快照信息

        按照下面的截图示例来获取界面快照，上传文件或者生成链接并粘贴到下面的输入框，如果是需要多个点击如 [点击关闭按钮->出现关闭弹窗->点击关闭原因] 这种类型，则需要填写每个点击界面的快照\
        ![img](https://raw.githubusercontent.com/Lin-arm/GKD_subscription/refs/heads/main/Snapshot.webp)
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ### ✅ 请您再次检查核对以下所有内容
        #### 为了节省时间提高处理效率，请您再次核对是否已严格按照上方要求操作。

  - type: checkboxes
    id: check-group
    attributes:
      label: 📋 检查
      description: 请确认以下检查项
      options:
        - label: 我已阅读 [不予适配情况合集](https://github.com/Lin-arm/GKD_subscription/issues/17)并确认没有**提及我想要适配的App**
          required: true
        - label: 我已**检查全局规则**并确认开启后**此App无法触发**规则
          required: true
        - label: 我已确认使用的是 **[最新版订阅](https://github.com/Lin-arm/GKD_subscription/releases/latest)** 和 **[最新版 GKD](https://github.com/gkd-kit/gkd/releases)**
          required: true

  - type: checkboxes
    id: snapshot-group
    attributes:
      label: 📸 快照要求
      description: 请确认快照已完整提供
      options:
        - label: 我已提供正确的**界面快照**（非截图）
          required: true
        - label: 如果是多次点击才能生效的情况，我已提供**每一次点击的快照**
          required: true

  - type: checkboxes
    id: other-group
    attributes:
      label: 📌 其他确认
      description: 请确认以下内容
      options:
        - label: 我已确认这个问题**属于本项目维护的规则**导致的（若不属于，已在说明中明确指出）
          required: true
